
#pragma config(Sensor, S1,     touchsensorR,        sensorTouch)
#pragma config(Sensor, S2,     threshold,           sensorSONAR)
#pragma config(Sensor, S3,     light,               sensorLightActive)
#pragma config(Sensor, S4,     touchsensorL,        sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
  long lite;
  long thres;
  int touchL;
  int touchR;
  bool pressedL = false;
  bool pressedR = false;
  bool lift = false;
  // wait1Msec(3000); // a three second delay


  while(true){
    thres = SensorValue(threshold);
    lite = SensorValue(light);
    touchL = SensorValue(touchsensorL);
    touchR = SensorValue(touchsensorR);
    int n = random(3);

    if((lite < 60) && (thres < 30) && (lift == true)){ // down the lift
       nMotorEncoder[motorB] = 0;
       nMotorEncoderTarget[motorB] = 30;
       motor[motorB] = 50;
       lift = false;
    }

    else{
    }

    if ((lite < 60) && (thres < 30)){ // close to enemy & on safe ground
      motor[motorA] = 20;
      motor[motorC] = 20;
    }

    else{ // default
      motor[motorA] = 0;
      motor[motorC] = 0;
    }

    if ((lite > 10) && (thres < 15) && (lift == false)){ // lift over enemy
      nVolume = 4;
      PlaySoundFile("Woops.rso");
      nMotorEncoder[motorB] = 0;
      nMotorEncoderTarget[motorB] = -30;
      motor[motorB] = -100;
      lift = true;
    }

    else {
    }

    if(touchL == 1){ // if touch LEFT, return pressedL TRUE & try to unpress touchL
        pressedL = true;
        motor[motorA] = 30;
        motor[motorC] = 30;
    }
      
    else{
    }

    if(touchR == 1){ // if touch RIGHT, return pressedR TRUE & try to unpress touchR
        pressedR = true;
        motor[motorA] = 30;
        motor[motorC] = 30;
    }

    else{
    }

    if ((touchL == 0) && (pressedL == true)){ // when the enemy bump LEFT, turn its behind
	    nMotorEncoder[motorA] = 0;
	    nMotorEncoder[motorC] = 0;
	    nMotorEncoderTarget[motorA] = 1440;
	    nMotorEncoderTarget[motorC] = 720;
	    motor[motorA] = 100;
	    motor[motorC] = 50;
	    if((lite < 60) && (thres < 30)){ // on safe ground & close to enemy, return FALSE
	      pressedL = false;
	    }
	    else{
	    }
	    if(lite > 60){ // on dangerous ground, return FALSE
	      pressedL = false;
	    }
	    else{
	    }
    }

   else{
   }

   if((touchR == 0) && (pressedR == true)){ // when the enemy bump RIGHT, turn its behind
        nMotorEncoder[motorA] = 0;
	    nMotorEncoder[motorC] = 0;
	    nMotorEncoderTarget[motorA] = 720;
	    nMotorEncoderTarget[motorC] = 1440;
	    motor[motorA] = 50;
	    motor[motorC] = 100;
	    if((lite < 60) && (thres < 30)){ // on safe ground & close to enemy, return FALSE
	      pressedR = false;
	    }
	    else{
	    }
	    if(lite > 60){ // on dangerous ground, return FALSE
	      pressedR = false;
	    }
	    else{
	    }
   }

   else{
   }

      if((lite > 60) && (n == 1)){ // on dangerous ground LEFT
      nVolume = 4;
      PlaySoundFile("turnOffTheLight.rso");
      motor[motorA] = -15;
      motor[motorC] = -15;
      wait1Msec(2000);
      motor[motorA] = 15;
      motor[motorC] = -15;
      srand(2500);
      wait1Msec(random(4000));
    }

    else{
    }

    if((lite > 60) && (n == 2)){ // on dangerous ground RIGHT
      nVolume = 4;
      PlaySoundFile("turnOffTheLight.rso");
      motor[motorA] = -15;
      motor[motorC] = -15;
      wait1Msec(2000);
      motor[motorA] = -15;
      motor[motorC] = 15;
      srand(2600);
      wait1Msec(random(4000));
   }

   else{
   }

 }}
