#pragma config(Sensor, S1,     touchsensorR,        sensorTouch)
#pragma config(Sensor, S2,     threshold,           sensorSONAR)
#pragma config(Sensor, S3,     light,               sensorLightActive)
#pragma config(Sensor, S4,     touchsensorL,        sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// VS program Ver.B (VS Sophia's Team) keep escaping and wait opponent's vulnerability fail
task main(){
  long lite;
  long thres;
  int touchL;
  int touchR;
  bool pressedL = false;
  bool pressedR = false;
  bool lift = false;
  nVolume = 4;
  // a three second delay with sound effect
  wait1Msec(500);
  PlaySoundFile("kissMyAss.rso");
  wait1Msec(2500);

  while(true){
    thres = SensorValue(threshold);
    lite = SensorValue(light);
    touchL = SensorValue(touchsensorL);
    touchR = SensorValue(touchsensorR);
    int nLR = random(3); // if something wrong, try **int nLR = random(2)+1**
    int nWait = random(1000);

// down the lift
    if((lite < 30) && (thres < 30) && (lift == true)){  //LITE MUST BE LOW BECAUSE OF ABSENT OF LIFT
       nMotorEncoder[motorB] = 0;
       nMotorEncoderTarget[motorB] = 30;
       motor[motorB] = 50;
       lift = false;
    }

    else{
    }
// if close to enemy, turn LEFT or RIGHT to avoid collision.
    if ((lite < 30) && (thres < 30) && (nLR == 1)){ // close to enemy & on safe ground, turn LEFT
      nMotorEncoder[motorA] = 0;
      nMotorEncoder[motorC] = 0;
      nMotorEncoderTarget[motorA] = -50;
      nMotorEncoderTarget[motorC] = 50;
      motor[motorA] = -60;
      motor[motorC] = 60;
    }

    else{ // default
      motor[motorA] = 50;
      motor[motorC] = 50;
    }

    if ((lite < 30) && (thres < 30) && (nLR == 2)){ // close to enemy & on safe ground, turn RIGHT
      nMotorEncoder[motorA] = 0;
      nMotorEncoder[motorC] = 0;
      nMotorEncoderTarget[motorA] = 50;
      nMotorEncoderTarget[motorC] = -50;
      motor[motorA] = 60;
      motor[motorC] = -60;
    }

    else{ // default
      motor[motorA] = 50;
      motor[motorC] = 50;
    }

 // lift over enemy
    if ((lite < 30) && (thres < 15) && (lift == false)){ //PROB LITE DIFFER WHEN LIFT IS UP
      nMotorEncoder[motorB] = 0;
      nMotorEncoderTarget[motorB] = -30;
      motor[motorB] = -100;
      lift = true;
    }

    else {
    }

    if(touchL == 1){ // if touch LEFT, return pressedL TRUE & try to unpress touchL
        pressedL = true;
        motor[motorA] = 100;
        motor[motorC] = 100;
    }

    else{
    }

    if(touchR == 1){ // if touch RIGHT, return pressedR TRUE & try to unpress touchR
        pressedR = true;
        motor[motorA] = 100;
        motor[motorC] = 100;
    }

    else{
    }

    if ((touchL == 0) && (pressedL == true)){ // when the enemy bump LEFT, turn its side
	    nMotorEncoder[motorA] = 0;
	    nMotorEncoder[motorC] = 0;
	    nMotorEncoderTarget[motorA] = 900;
	    nMotorEncoderTarget[motorC] = 900;
	    motor[motorA] = 100;
	    motor[motorC] = 100;
	    if((lite < 30) && (thres < 30)){ // on safe ground & close to enemy, return FALSE
	      pressedL = false;
	    }
	    else{
	    }
	    if(lite > 30){ // on dangerous ground, return FALSE
	      pressedL = false;
	    }
	    else{
	    }
    }

   else{
   }

   if((touchR == 0) && (pressedR == true)){ // when the enemy bump RIGHT, turn its side
      nMotorEncoder[motorA] = 0;
	    nMotorEncoder[motorC] = 0;
	    nMotorEncoderTarget[motorA] = 900;
	    nMotorEncoderTarget[motorC] = 900;
	    motor[motorA] = 100;
	    motor[motorC] = 100;
	    if((lite < 30) && (thres < 30)){ // on safe ground & close to enemy, return FALSE
	      pressedR = false;
	    }
	    else{
	    }
	    if(lite > 30){ // on dangerous ground, return FALSE
	      pressedR = false;
	    }
	    else{
	    }
   }

   else{
   }

      if((lite > 30) && (nLR == 1) && (nWait > 500) && (nWait < 1000)){ // on dangerous ground LEFT
      nVolume = 4;
      PlaySoundFile("turnOffTheLight.rso");
      motor[motorA] = -100;
      motor[motorC] = -100;
      wait1Msec(500);
      motor[motorA] = 70;
      motor[motorC] = -70;
      // srand(450);
      wait1Msec(nWait);
    }

    else{
    }

    if((lite > 30) && (nLR == 2)&& (nWait > 500) && (nWait < 1000)){ // on dangerous ground RIGHT
      nVolume = 4;
      PlaySoundFile("Woops.rso");
      motor[motorA] = -100;
      motor[motorC] = -100;
      wait1Msec(500);
      motor[motorA] = -70;
      motor[motorC] = 70;
      // srand(450);
      wait1Msec(nWait);
   }

   else{
   }

 }}
